DROP TABLE IF EXISTS `expensetypefile`;
CREATE TABLE `expensetypefile` (
  `recid` int(11) NOT NULL AUTO_INCREMENT,
  `expense_dsc` varchar(100) DEFAULT NULL,
  `expense_cde` varchar(100) NOT NULL,
  PRIMARY KEY (`recid`),
  UNIQUE KEY `expense_cde` (`expense_cde`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `mf_advanced_by`;
CREATE TABLE `mf_advanced_by` (
  `recid` int(11) NOT NULL AUTO_INCREMENT,
  `advanced_by_cde` varchar(100) NOT NULL,
  `advanced_by_dsc` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`recid`),
  UNIQUE KEY `advanced_by_cde` (`advanced_by_cde`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `vat_typefile`;
CREATE TABLE `vat_typefile` (
  `recid` int(11) NOT NULL AUTO_INCREMENT,
  `vat_dsc` varchar(100) DEFAULT NULL,
  `vat_cde` varchar(100) NOT NULL,
  PRIMARY KEY (`recid`),
  UNIQUE KEY `vat_cde` (`vat_cde`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



DROP TABLE IF EXISTS `expensefile1`;
CREATE TABLE `expensefile1` (
  `recid` bigint(11) NOT NULL AUTO_INCREMENT,
  `docnum` varchar(25) NOT NULL,
  `trndte` date DEFAULT NULL,
  `suppcde` varchar(100) DEFAULT NULL,
  `expense_cde` varchar(100) DEFAULT NULL,
  `vat_cde` varchar(100) DEFAULT NULL,
  `advanced_by_cde` varchar(100) DEFAULT NULL,
  `paydate` date DEFAULT NULL,
  `paydetails` varchar(150) DEFAULT NULL,
  `payment_status` varchar(100) DEFAULT NULL,
  `remarks` varchar(150) DEFAULT NULL,
  `trntot` double DEFAULT NULL,
  PRIMARY KEY (`recid`),
  KEY `vat_cde` (`vat_cde`),
  KEY `expense_cde` (`expense_cde`),
  KEY `advanced_by_cde` (`advanced_by_cde`),
  CONSTRAINT `expensefile1_ibfk_4` FOREIGN KEY (`vat_cde`) REFERENCES `vat_typefile` (`vat_cde`) ON DELETE CASCADE,
  CONSTRAINT `expensefile1_ibfk_5` FOREIGN KEY (`expense_cde`) REFERENCES `expensetypefile` (`expense_cde`) ON DELETE CASCADE,
  CONSTRAINT `expensefile1_ibfk_6` FOREIGN KEY (`advanced_by_cde`) REFERENCES `mf_advanced_by` (`advanced_by_cde`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS `purchasesorderfile1`;
CREATE TABLE `purchasesorderfile1` (
  `docnum` varchar(25) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `cusdsc` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `trndte` date DEFAULT NULL,
  `trmdsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `smndsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `shipto` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `trncde` varchar(3) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `trntot` double DEFAULT '0',
  `duedate` datetime DEFAULT NULL,
  `smncde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `trmcde` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `suppcde` varchar(100) CHARACTER SET utf8 DEFAULT '',
  `cusgrp` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `curcde` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT 'PHP',
  `comcde` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `usrnam` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `currte` double DEFAULT '1',
  `prccde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `sonum` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `shipto2` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `vatamt` double DEFAULT '0',
  `vatrte` double DEFAULT '0',
  `othchatot` double DEFAULT '0',
  `textprc` double DEFAULT '0',
  `logtim` datetime DEFAULT NULL,
  `logdte` datetime DEFAULT NULL,
  `trmtypcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `trmtypdsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `othchatotfor` double DEFAULT '0',
  `trntotfor` double DEFAULT '0',
  `textprcfor` double DEFAULT '0',
  `remarks` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `vat` int(11) DEFAULT '0',
  `ewtrte` int(11) DEFAULT '0',
  `taxcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `refnum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `docapp` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `docbal` double DEFAULT '0',
  `setdocbal` double DEFAULT '0',
  `totpdc` double DEFAULT '0',
  `settotpdc` double DEFAULT '0',
  `amtapp` double DEFAULT '0',
  `lastpaydte` datetime DEFAULT NULL,
  `memtypcde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `manualgl` int(11) DEFAULT '0',
  `ewtamt` double DEFAULT '0',
  `pretaxamt` double DEFAULT '0',
  `pretaxrte` double DEFAULT '0',
  `netvatamt` double DEFAULT '0',
  `ewtcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `docbalfor` double DEFAULT '0',
  `vatableamt` double DEFAULT '0',
  `vatexemptamt` double DEFAULT '0',
  `vatzeroratedamt` double DEFAULT '0',
  `nonvat` double DEFAULT '0',
  `chknonvat` int(11) DEFAULT '0',
  `gainloss` double DEFAULT '0',
  `manualvat` int(11) DEFAULT '0',
  `setdocbalfor` double DEFAULT '0',
  `settotpdcfor` double DEFAULT '0',
  `busstyle` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `remarks1` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `tinnum` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `canceldoc` int(11) DEFAULT '0',
  `vatamtfor` double DEFAULT '0',
  `netvatamtfor` double DEFAULT '0',
  `vatableamtfor` double DEFAULT '0',
  `vatexemptamtfor` double DEFAULT '0',
  `vatzeroratedamtfor` double DEFAULT '0',
  `nonvatfor` double DEFAULT '0',
  `canceldte` datetime DEFAULT NULL,
  `orderby` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `projname` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `projsite` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `ra` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `radte` datetime DEFAULT NULL,
  `sibill` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `billtype` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `siremarks` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `salesengr` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `preby` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `chkby` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `apvby` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `delconfnum` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `ffrom` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `aprdte` datetime DEFAULT NULL,
  `chkasy` int(11) DEFAULT '0',
  `chkewt` tinyint(4) NOT NULL,
  `totamtdis` double DEFAULT '0',
  `totgroext` double DEFAULT '0',
  `totamtdisfor` double DEFAULT '0',
  `totgroextfor` double DEFAULT '0',
  `netamt` double DEFAULT '0',
  `netamtfor` double DEFAULT '0',
  `ponum` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `increp` varchar(1) COLLATE latin1_general_ci DEFAULT NULL,
  `pcknum` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `cusgrpcde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `cusadd1` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `cusadd2` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field01` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field02` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field03` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field04` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field05` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field06` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field07` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field08` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field09` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field10` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field11` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field12` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field13` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field14` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field15` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field16` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field17` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field18` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field19` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field20` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `manualewt` int(11) DEFAULT '0',
  `bilnum` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `doclock` varchar(1) COLLATE latin1_general_ci DEFAULT 'N',
  `bnkcde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `chknum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `voudocnum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `recid` bigint(11) NOT NULL AUTO_INCREMENT,
  `cancelrem` varchar(200) COLLATE latin1_general_ci DEFAULT NULL,
  `drdte` datetime DEFAULT NULL,
  `prttyp` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `warcde` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `gldepcde` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `reqby` char(25) COLLATE latin1_general_ci DEFAULT '',
  `ewtamtfor` double DEFAULT '0',
  `budgetalloc` int(1) DEFAULT '0',
  `status` varchar(15) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `usrcde` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `custypcde` varchar(30) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `frm_billing` int(11) DEFAULT '0',
  `billmonth` int(11) DEFAULT '0',
  `billyear` int(11) DEFAULT '0',
  `billtyp` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `proposalamount` decimal(18,5) DEFAULT '0.00000',
  `fromproposal` int(11) DEFAULT '0',
  `prop_cuscde` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `prodcde` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `paydate` date DEFAULT NULL,
  `paydetails` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `ordernum` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `po_qr_id` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `po_qr_date_scanned` date DEFAULT NULL,
  PRIMARY KEY (`recid`),
  UNIQUE KEY `salfle1_idx1` (`docnum`,`trncde`),
  KEY `salfle1_idx2` (`suppcde`),
  KEY `NewIndex1` (`docapp`),
  CONSTRAINT `purchasesorderfile1_ibfk_2` FOREIGN KEY (`suppcde`) REFERENCES `supplierfile` (`suppcde`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


DROP TABLE IF EXISTS `purchasesorderfile2`;
CREATE TABLE `purchasesorderfile2` (
  `docnum` varchar(25) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `tranfile2_recid` int(11) DEFAULT NULL,
  `cusdsc` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `trndte` datetime DEFAULT NULL,
  `itmcde` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `itmdsc` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `itmqty` double DEFAULT '0',
  `untprc` double DEFAULT '0',
  `extprc` double DEFAULT '0',
  `trncde` varchar(3) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `untmea` varchar(5) COLLATE latin1_general_ci DEFAULT NULL,
  `prcdst1` double DEFAULT '0',
  `prcdst2` double DEFAULT '0',
  `prcdst3` double DEFAULT '0',
  `wardsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `factor` double DEFAULT '0',
  `linenum` int(11) DEFAULT '0',
  `suppcde` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `warcde` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `groprc` double DEFAULT '0',
  `prccde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `sonum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `disamt` double DEFAULT '0',
  `conver1` double DEFAULT '0',
  `smncde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `smndsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `usrnam` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `logtim` datetime DEFAULT NULL,
  `logdte` datetime DEFAULT NULL,
  `trmtypcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `trmtypdsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `curcde` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT 'PHP',
  `currte` double DEFAULT '1',
  `disamtfor` double DEFAULT '0',
  `untprcfor` double DEFAULT '0',
  `groprcfor` double DEFAULT '0',
  `extprcfor` double DEFAULT '0',
  `untcst` double DEFAULT '0',
  `extcst` double DEFAULT '0',
  `sernum` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `drnum` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `disper` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `lstcst` double DEFAULT '0',
  `extlst` double DEFAULT '0',
  `avecst` double DEFAULT '0',
  `extave` double DEFAULT '0',
  `fifcst` double DEFAULT '0',
  `extfif` double DEFAULT '0',
  `itmtyp` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `netvatamt` double DEFAULT '0',
  `taxcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `vatamt` double DEFAULT '0',
  `vatrte` double DEFAULT '0',
  `ewtamt` double DEFAULT '0',
  `evatamt` double DEFAULT '0',
  `ewtcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `ewtrte` double DEFAULT '0',
  `evatcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `evatrte` double DEFAULT '0',
  `itmrem1` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `itmrem2` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `itmrem3` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `netvatamtfor` double DEFAULT '0',
  `vatamtfor` double DEFAULT '0',
  `chkewt` int(11) DEFAULT '0',
  `amtdis` double DEFAULT '0',
  `groext` double DEFAULT '0',
  `amtdisfor` double DEFAULT '0',
  `groextfor` double DEFAULT '0',
  `refnum` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `increp` varchar(1) COLLATE latin1_general_ci DEFAULT NULL,
  `cusgrpcde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `cusitmcde` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `dettyp` varchar(1) COLLATE latin1_general_ci DEFAULT 'i',
  `recid` int(11) NOT NULL AUTO_INCREMENT,
  `linegrp` int(11) DEFAULT '0',
  `chkasy` int(11) DEFAULT '0',
  `drdte` datetime DEFAULT NULL,
  `field01` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field02` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field03` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field04` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field05` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field06` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field07` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field08` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field09` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field10` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field11` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field12` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field13` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field14` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field15` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field16` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field17` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field18` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field19` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field20` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `pckitmcde` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `copyline` int(11) DEFAULT '0',
  `scpwddis` double DEFAULT NULL,
  `barcodenum` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `custypcde` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  PRIMARY KEY (`recid`),
  KEY `salfle2_idx1` (`docnum`),
  KEY `salfle2_idx2` (`itmcde`,`untmea`,`warcde`),
  KEY `salfle2_idx3` (`sonum`,`itmcde`,`untmea`),
  KEY `trndte` (`trndte`),
  KEY `cuscde` (`suppcde`),
  KEY `ItmCde` (`itmcde`),
  KEY `DocNum` (`docnum`),
  CONSTRAINT `purchasesorderfile2_ibfk_1` FOREIGN KEY (`docnum`) REFERENCES `purchasesorderfile1` (`docnum`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


DROP TABLE IF EXISTS `salesorderfile1`;
CREATE TABLE `salesorderfile1` (
  `docnum` varchar(25) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `salnum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `waybill_number` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `file_convert_id` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `file_ordernum` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `ordernum` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `order_status` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `file_created_date` datetime DEFAULT NULL,
  `file_lineitem_name` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `cusdsc` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `trndte` date DEFAULT NULL,
  `trmdsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `smndsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `shipto` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `trncde` varchar(3) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `trntot` double DEFAULT '0',
  `duedate` datetime DEFAULT NULL,
  `smncde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `trmcde` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `cuscde` varchar(100) CHARACTER SET utf8 DEFAULT '',
  `cusgrp` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `curcde` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT 'PHP',
  `comcde` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `usrnam` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `currte` double DEFAULT '1',
  `prccde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `sonum` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `shipto2` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `vatamt` double DEFAULT '0',
  `vatrte` double DEFAULT '0',
  `othchatot` double DEFAULT '0',
  `textprc` double DEFAULT '0',
  `logtim` datetime DEFAULT NULL,
  `logdte` datetime DEFAULT NULL,
  `trmtypcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `trmtypdsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `othchatotfor` double DEFAULT '0',
  `trntotfor` double DEFAULT '0',
  `textprcfor` double DEFAULT '0',
  `remarks` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `vat` int(11) DEFAULT '0',
  `ewtrte` int(11) DEFAULT '0',
  `taxcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `refnum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `docapp` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `docbal` double DEFAULT '0',
  `setdocbal` double DEFAULT '0',
  `totpdc` double DEFAULT '0',
  `settotpdc` double DEFAULT '0',
  `amtapp` double DEFAULT '0',
  `lastpaydte` datetime DEFAULT NULL,
  `memtypcde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `manualgl` int(11) DEFAULT '0',
  `ewtamt` double DEFAULT '0',
  `pretaxamt` double DEFAULT '0',
  `pretaxrte` double DEFAULT '0',
  `netvatamt` double DEFAULT '0',
  `ewtcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `docbalfor` double DEFAULT '0',
  `vatableamt` double DEFAULT '0',
  `vatexemptamt` double DEFAULT '0',
  `vatzeroratedamt` double DEFAULT '0',
  `nonvat` double DEFAULT '0',
  `chknonvat` int(11) DEFAULT '0',
  `gainloss` double DEFAULT '0',
  `manualvat` int(11) DEFAULT '0',
  `setdocbalfor` double DEFAULT '0',
  `settotpdcfor` double DEFAULT '0',
  `busstyle` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `remarks1` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `tinnum` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `canceldoc` int(11) DEFAULT '0',
  `vatamtfor` double DEFAULT '0',
  `netvatamtfor` double DEFAULT '0',
  `vatableamtfor` double DEFAULT '0',
  `vatexemptamtfor` double DEFAULT '0',
  `vatzeroratedamtfor` double DEFAULT '0',
  `nonvatfor` double DEFAULT '0',
  `canceldte` datetime DEFAULT NULL,
  `orderby` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `projname` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `projsite` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `ra` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `radte` datetime DEFAULT NULL,
  `sibill` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `billtype` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `siremarks` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `salesengr` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `preby` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `chkby` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `apvby` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `delconfnum` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `ffrom` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `aprdte` datetime DEFAULT NULL,
  `chkasy` int(11) DEFAULT '0',
  `chkewt` tinyint(4) NOT NULL,
  `totamtdis` double DEFAULT '0',
  `totgroext` double DEFAULT '0',
  `totamtdisfor` double DEFAULT '0',
  `totgroextfor` double DEFAULT '0',
  `netamt` double DEFAULT '0',
  `netamtfor` double DEFAULT '0',
  `ponum` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `increp` varchar(1) COLLATE latin1_general_ci DEFAULT NULL,
  `pcknum` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `cusgrpcde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `cusadd1` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `cusadd2` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field01` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field02` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field03` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field04` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field05` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field06` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field07` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field08` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field09` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field10` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field11` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field12` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field13` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field14` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field15` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field16` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field17` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field18` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field19` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field20` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `manualewt` int(11) DEFAULT '0',
  `bilnum` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `doclock` varchar(1) COLLATE latin1_general_ci DEFAULT 'N',
  `bnkcde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `chknum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `voudocnum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `recid` bigint(11) NOT NULL AUTO_INCREMENT,
  `cancelrem` varchar(200) COLLATE latin1_general_ci DEFAULT NULL,
  `drdte` datetime DEFAULT NULL,
  `prttyp` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `warcde` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `gldepcde` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `reqby` char(25) COLLATE latin1_general_ci DEFAULT '',
  `ewtamtfor` double DEFAULT '0',
  `budgetalloc` int(1) DEFAULT '0',
  `status` varchar(15) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `usrcde` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `custypcde` varchar(30) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `frm_billing` int(11) DEFAULT '0',
  `billmonth` int(11) DEFAULT '0',
  `billyear` int(11) DEFAULT '0',
  `billtyp` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `proposalamount` decimal(18,5) DEFAULT '0.00000',
  `fromproposal` int(11) DEFAULT '0',
  `prop_cuscde` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `prodcde` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `buyer_id` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  PRIMARY KEY (`recid`),
  UNIQUE KEY `salfle1_idx1` (`docnum`,`trncde`),
  KEY `salfle1_idx2` (`cuscde`),
  KEY `NewIndex1` (`docapp`),
  CONSTRAINT `salesorderfile1_ibfk_2` FOREIGN KEY (`cuscde`) REFERENCES `customerfile` (`cuscde`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


DROP TABLE IF EXISTS `salesorderfile2`;
CREATE TABLE `salesorderfile2` (
  `docnum` varchar(25) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `file_ordernum` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `file_created_date` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `file_lineitem_name` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `cusdsc` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `trndte` datetime DEFAULT NULL,
  `itmcde` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `itmdsc` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `itmqty` double DEFAULT '0',
  `untprc` double DEFAULT '0',
  `extprc` double DEFAULT '0',
  `trncde` varchar(3) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `bom_item` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `bom_linenum` int(11) DEFAULT NULL,
  `untmea` varchar(5) COLLATE latin1_general_ci DEFAULT NULL,
  `prcdst1` double DEFAULT '0',
  `prcdst2` double DEFAULT '0',
  `prcdst3` double DEFAULT '0',
  `wardsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `factor` double DEFAULT '0',
  `linenum` int(11) DEFAULT '0',
  `cuscde` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `warcde` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `groprc` double DEFAULT '0',
  `prccde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `sonum` varchar(25) COLLATE latin1_general_ci DEFAULT NULL,
  `disamt` double DEFAULT '0',
  `conver1` double DEFAULT '0',
  `smncde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `smndsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `usrnam` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `logtim` datetime DEFAULT NULL,
  `logdte` datetime DEFAULT NULL,
  `trmtypcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `trmtypdsc` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `curcde` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT 'PHP',
  `currte` double DEFAULT '1',
  `disamtfor` double DEFAULT '0',
  `untprcfor` double DEFAULT '0',
  `groprcfor` double DEFAULT '0',
  `extprcfor` double DEFAULT '0',
  `untcst` double DEFAULT '0',
  `extcst` double DEFAULT '0',
  `sernum` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `drnum` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `disper` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `lstcst` double DEFAULT '0',
  `extlst` double DEFAULT '0',
  `avecst` double DEFAULT '0',
  `extave` double DEFAULT '0',
  `fifcst` double DEFAULT '0',
  `extfif` double DEFAULT '0',
  `itmtyp` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `netvatamt` double DEFAULT '0',
  `taxcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `vatamt` double DEFAULT '0',
  `vatrte` double DEFAULT '0',
  `ewtamt` double DEFAULT '0',
  `evatamt` double DEFAULT '0',
  `ewtcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `ewtrte` double DEFAULT '0',
  `evatcde` varchar(15) COLLATE latin1_general_ci DEFAULT NULL,
  `evatrte` double DEFAULT '0',
  `itmrem1` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `itmrem2` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `itmrem3` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `netvatamtfor` double DEFAULT '0',
  `vatamtfor` double DEFAULT '0',
  `chkewt` int(11) DEFAULT '0',
  `amtdis` double DEFAULT '0',
  `groext` double DEFAULT '0',
  `amtdisfor` double DEFAULT '0',
  `groextfor` double DEFAULT '0',
  `refnum` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `increp` varchar(1) COLLATE latin1_general_ci DEFAULT NULL,
  `cusgrpcde` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `cusitmcde` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `dettyp` varchar(1) COLLATE latin1_general_ci DEFAULT 'i',
  `recid` int(11) NOT NULL AUTO_INCREMENT,
  `linegrp` int(11) DEFAULT '0',
  `chkasy` int(11) DEFAULT '0',
  `drdte` datetime DEFAULT NULL,
  `field01` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field02` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field03` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field04` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field05` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field06` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field07` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field08` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field09` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field10` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field11` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field12` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field13` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field14` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field15` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field16` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field17` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field18` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field19` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `field20` varchar(150) COLLATE latin1_general_ci DEFAULT NULL,
  `pckitmcde` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `copyline` int(11) DEFAULT '0',
  `scpwddis` double DEFAULT NULL,
  `barcodenum` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `custypcde` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  PRIMARY KEY (`recid`),
  KEY `salfle2_idx1` (`docnum`),
  KEY `salfle2_idx2` (`itmcde`,`untmea`,`warcde`),
  KEY `salfle2_idx3` (`sonum`,`itmcde`,`untmea`),
  KEY `trndte` (`trndte`),
  KEY `cuscde` (`cuscde`),
  KEY `ItmCde` (`itmcde`),
  KEY `DocNum` (`docnum`),
  CONSTRAINT `salesorderfile2_ibfk_1` FOREIGN KEY (`docnum`) REFERENCES `salesorderfile1` (`docnum`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;




-- 2025-05-26 10:32:29
